name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Bazel
        uses: ngalaiko/bazel-action/2.0.0@master

      - name: Test with Maven
        run: ./mvnw -B verify -f pom.xml

      - name: Build with Maven
        if: github.ref != 'refs/heads/master'
        run: ./mvnw -B package -f pom.xml -DskipTests

      - name: Publish artifacts to Maven repo
        env:
          NEXUS_HOST: ${{ secrets.NEXUS_HOST }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        if: github.ref == 'refs/heads/master'
        run: ./mvnw -B deploy -f pom.xml -s settings.xml -DskipTests

      - name: Publish p2 repository
        env:
          NEXUS_HOST: ${{ secrets.NEXUS_HOST }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        if: github.ref == 'refs/heads/master'
        run: ./mvnw -B site-deploy -f pom.xml -s settings.xml
