name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Mount bazel cache
        uses: actions/cache@v1
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel

      - name: Install Bazel
        run: |
          curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
          echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt update && sudo apt install bazel

      - name: Check policies
        run: ./mvnw -B validate -f pom.xml

      - name: Test with Maven
        run: ./mvnw -B verify -f pom.xml

      - name: Build with Maven
        run: ./mvnw -B package -f pom.xml -DskipTests

      - name: Prepare p2 repository
        run: |
          cp -avr ./com.salesforce.b2eclipse.repository/target/repository ./repository
          git add -f repository/*
          git stash
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git symbolic-ref HEAD refs/heads/gh-pages
          rm .git/index
          git clean -fdx
          git stash pop
          git commit -m "Publish p2 repo to GitHub Pages" -a

      - name: Publish p2 repository
        if: github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
